polygon:
date_start: '19800101'
date_stop:
collections: ["OPERA_L3_DSWX-HLS_V1_1.0", "OPERA_L3_DSWX-S1_V1_1.0"]
swot_collections: ["SWOT_L2_HR_Raster_2.0"]
dataDir_dsw: ./data/DSW
dataDir_swot: ./data/swot
demPath: none
dataDir_usgs: ./data/salina_dswe
workdir: ./
cloudy_threshold: 100
water_levels_csv: none
