# create environment : conda env create -f requirements.yaml
# update dependencies: conda env update -f requirements.yaml
# remove environment : conda env remove -n swampy
# enter  environment : conda activate swampy
# exit   environment : conda deactivate

name: swampy
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - rasterio
  - scipy
  - requests
  - shapely
  - geopandas
  - pandas
  - cartopy
  - yaml
  - pystac-client
  - netcdf4
  - earthaccess
  - contextily
  - cdsapi
  - xarray
  - imageio
  - scikit-image
  - gdal
  - pyproj
